name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build Test
      id: build-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Build Test
        setup-command: ''
        command: "./gradlew build"
        timeout: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUILD-TEST_RESULTS: "${{steps.build-test.outputs.result}}"
      with:
        runners: build-test
